language: rust

addons:
  apt:
    sources:
    - sourceline: 'ppa:exonum/rocksdb'
    - sourceline: 'ppa:maarten-fonville/protobuf'
    - sourceline: 'ppa:fsgmhoward/shadowsocks-libev'
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/16.04/prod xenial main'
      key_url: https://packages.microsoft.com/keys/microsoft.asc
    packages:
    - binutils-dev
    - build-essential
    - cmake
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libdw-dev
    - libelf-dev
    - libiberty-dev
    - libprotobuf-dev
    - librocksdb5.17
    - libsnappy-dev
    - libsodium-dev
    - libssl-dev
    - pkg-config
    - powershell
    - protobuf-compiler
    - unzip
    - zlib1g-dev

rust:
  - 1.38.0

cache:
  npm: true
  directories:
  - $HOME/.local
  - $HOME/.cargo
  - $HOME/.kcov
  - $TRAVIS_BUILD_DIR/target
  timeout: 900

dist: xenial
sudo: required

env:
  global:
  - DEADLINKS_VERS=0.3.0
  - RUSTFLAGS="-D warnings"
  - ROCKSDB_LIB_DIR=/usr/lib
  - SNAPPY_LIB_DIR=/usr/lib/x86_64-linux-gnu
jobs:
  include:
  # Formatting & other lints that do not require compilation
  - name: lints
    install:
    - rustup component add rustfmt
    - rustfmt -V
    - nvm install 8 && nvm use 8
    - npm install
    - ./node_modules/.bin/cspell --version
    - ./node_modules/.bin/markdownlint --version
    script:
    - cargo fmt -- --check
    - npm run cspell
    - npm run md

  # Clippy linting
  - name: clippy
    install:
    - rustup component add clippy
    - cargo clippy --version
    script:
    - cargo clippy --all -- -D warnings

  # Tests
  - name: linux-tests
    script:
    - cargo test --all

  # Non-fatal checks
  - name: deadlinks
    env: FEATURE=non-fatal-checks
    install:
    - cargo-deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
    script:
    - cargo doc --no-deps
    - cargo deadlinks --dir target/doc
    
before_cache:
  - |
    cd $TRAVIS_BUILD_DIR/target/debug
    rm -rf incremental examples
    find . -maxdepth 1 -type f -executable -delete
    find deps -type f -size +20M -delete
    du -h -d 1 .
